name: config_run_687
render: false
vis_debug: false
seed: 8
max_env_steps: 20
env:
  _target_: vtamp.environments.raven_ycb.env.RavenYCBEnv
  stability_check: False
  gui: true
task:
  _target_: vtamp.environments.raven_ycb.tasks.PackingYCB
  goal_str: "Place all of the items within 0.06 of the center of the table in a square region"
  task_name: YCB-Packing
policy:
  _target_: vtamp.policies.llm3.policy.LLM3
  max_feedbacks: 5
  max_csp_samples: 1000
  gaussian_blur: true
  method: llm3-gaussian
updater:
  _target_: vtamp.environments.raven.env.RavenGroundTruthBeliefUpdater