name: config_run_591
render: false
vis_debug: false
seed: 2
max_env_steps: 20
env:
  _target_: vtamp.environments.raven_ycb.env.RavenYCBEnv
  stability_check: True
  gui: true
task:
  _target_: vtamp.environments.raven_ycb.tasks.StackingYCB
  goal_str: "Stack any object on any other object"
  task_name: YCB-Stacking
policy:
  _target_: vtamp.policies.code_as_policies.policy.CaP
  max_feedbacks: 0
  max_csp_samples: 250
  gaussian_blur: true
  method: cap-gaussian
updater:
  _target_: vtamp.environments.raven.env.RavenGroundTruthBeliefUpdater