name: config_run_481
render: false
vis_debug: false
seed: 2
max_env_steps: 20
env:
  _target_: vtamp.environments.raven_ycb.env.RavenYCBEnv
  stability_check: False
  gui: true
task:
  _target_: vtamp.environments.raven_ycb.tasks.PackingYCB
  goal_str: "Place all of the items within 0.06 of the center of the table in a square region"
  task_name: YCB-Packing
policy:
  _target_: vtamp.policies.llm3.policy.LLM3
  max_feedbacks: 0
  max_csp_samples: 1000
  gaussian_blur: false
  method: llm3-nf
updater:
  _target_: vtamp.environments.raven.env.RavenGroundTruthBeliefUpdater