name: config_run_586
render: false
vis_debug: false
seed: 7
max_env_steps: 20
env:
  _target_: vtamp.environments.raven_ycb.env.RavenYCBEnv
  stability_check: False
  gui: true
task:
  _target_: vtamp.environments.raven_ycb.tasks.PackingYCB
  goal_str: "Place all of the items within 0.06 of the center of the table in a square region"
  task_name: YCB-Packing
policy:
  _target_: vtamp.policies.code_as_policies.policy.CaP
  max_feedbacks: 0
  max_csp_samples: 1000
  gaussian_blur: true
  method: cap-gaussian
updater:
  _target_: vtamp.environments.raven.env.RavenGroundTruthBeliefUpdater