name: config_run_46
render: false
vis_debug: false
seed: 7
max_env_steps: 20
env:
  _target_: vtamp.environments.raven.env.RavenEnv
  stability_check: True
  gui: true
task:
  _target_: vtamp.environments.raven.tasks.LineHard
  goal_str: "Stack a pyramid out of any three blocks"
  task_name: Pyramid
policy:
  _target_: vtamp.policies.ours.policy.Ours
  max_feedbacks: 5
  max_csp_samples: 250
  gaussian_blur: false
  method: ours
updater:
  _target_: vtamp.environments.raven.env.RavenGroundTruthBeliefUpdater