name: config_run_539
render: false
vis_debug: false
seed: 10
max_env_steps: 50
env:
  _target_: vtamp.environments.turtle.env.TurtleEnvEmbodied
  stability_check: False
  gui: true
task:
  _target_: vtamp.environments.turtle.env.DrawShape
  goal_str: "draw a rectangle that encloses any obstacle"
  task_name: Enclosed
policy:
  _target_: vtamp.policies.code_as_policies.policy.CaP
  max_feedbacks: 0
  max_csp_samples: 10000
  gaussian_blur: true
  method: cap-gaussian
updater:
  _target_: vtamp.environments.utils.DefaultUpdater