defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

name: cap_raven
render: true
vis_debug: false
seed: 1
max_env_steps: 10
env:
  _target_: vtamp.environments.raven.env.RavenEnv
task:
  _target_: vtamp.environments.raven.tasks.LineHard
  goal_str: "Put five blocks in a line flat on the table"
policy:
  _target_: vtamp.policies.code_as_policies.policy.CaP
  gaussian_blur: true
updater:
  _target_: vtamp.environments.raven.env.RavenGroundTruthBeliefUpdater