defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

name: ours_raven
render: true
vis_debug: false
seed: 0
max_env_steps: 10
env:
  _target_: vtamp.environments.raven.env.RavenEnv
task:
  _target_: vtamp.environments.raven.tasks.UnstackTask
policy:
  _target_: vtamp.policies.llm3.policy.LLM3
  max_feedbacks: 2
updater:
  _target_: vtamp.environments.raven.env.RavenGroundTruthBeliefUpdater