defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

name: ours_turtle
render: true
vis_debug: false
seed: 0
max_env_steps: 50
env:
  _target_: vtamp.environments.turtle.env.TurtleEnv
task:
  _target_: vtamp.environments.turtle.env.DrawShape
  goal_str: "draw a star"
policy:
  _target_: vtamp.policies.ours.policy.Ours
updater:
  _target_: vtamp.environments.utils.DefaultUpdater