defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

name: ours_raven
render: true
vis_debug: false
seed: 0
max_env_steps: 10
env:
  _target_: vtamp.environments.raven_ycb.env.RavenYCBEnv
task:
  _target_: vtamp.environments.raven_ycb.tasks.PackingYCB
  goal_str: "Place all objects within 0.06 of the center of the table"
policy:
  _target_: vtamp.policies.ours.policy.Ours
  max_csp_samples: 100
updater:
  _target_: vtamp.environments.raven_ycb.env.RavenGroundTruthBeliefUpdater