defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

name: ours_raven_packing
render: true
vis_debug: false
seed: 0
max_env_steps: 10
env:
  _target_: vtamp.environments.raven.env.RavenEnv
task:
  _target_: vtamp.environments.raven.tasks.StackInBowlTask
  goal_str: "Stack the yellow and green block inside of the bowl"
policy:
  _target_: vtamp.policies.ours.policy.Ours
  max_feedbacks: 5
  max_csp_samples: 15
updater:
  _target_: vtamp.environments.raven.env.RavenGroundTruthBeliefUpdater