defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

name: ours_raven
render: true
vis_debug: false
seed: 0
max_env_steps: 20
env:
  _target_: vtamp.environments.raven.env.RavenEnv
task:
  _target_: vtamp.environments.raven.tasks.LineHard
  goal_str: "Stack an upright pyramid out of three blocks"
policy:
  _target_: vtamp.policies.ours.policy.Ours
  max_feedbacks: 3
  max_csp_samples: 100
updater:
  _target_: vtamp.environments.raven.env.RavenGroundTruthBeliefUpdater