defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

name: ours_raven
render: true
vis_debug: false
seed: 4
max_env_steps: 10
env:
  _target_: vtamp.environments.raven_ycb.env.RavenYCBEnv
task:
  _target_: vtamp.environments.raven_ycb.tasks.StackingYCB
  goal_str: "Stack any object on any other object"
policy:
  _target_: vtamp.policies.ours.policy.Ours
  max_csp_samples: 100
  max_feedbacks: 5
updater:
  _target_: vtamp.environments.raven_ycb.env.RavenGroundTruthBeliefUpdater