defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

name: ours_raven
render: true
vis_debug: false
seed: 0
max_env_steps: 10
env:
  _target_: vtamp.environments.raven.env.RavenEnv
task:
  _target_: vtamp.environments.raven.tasks.CustomTask
  goal_str: "place the blocks as close to you as possible"
policy:
  _target_: vtamp.policies.ours.policy.Ours
  max_csp_samples: 10
  max_feedbacks: 10
updater:
  _target_: vtamp.environments.raven.env.RavenGroundTruthBeliefUpdater