defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

name: ours_raven
render: false
vis_debug: false
seed: 0
max_env_steps: 10
env:
  _target_: vtamp.environments.raven.env.RavenEnv
  robot_type: panda
  real_robot: false #true
  real_camera: false #true
  image_observations: false #true
task:
  _target_: vtamp.environments.raven.tasks.EmptyTask
  goal_str: "Put five blocks in a line flat on the table"
policy:
  _target_: vtamp.policies.ours.policy.Ours
  max_csp_samples: 100
  max_feedbacks: 5
updater:
  _target_: vtamp.environments.raven.env.RavenVisionBeliefUpdater